sudo: false

language: java
jdk: oraclejdk8
script:
- export TERM=dumb
- "./Src/java/gradlew --version"
- "./Src/java/gradlew --no-daemon -b ./Src/java/build.gradle check"
branches:
  only:
  - master
notifications:
  slack:
    secure: YFL4p/a/xkz7/vd9zTcJ8ClLrKytGGNiGrT/wCYaqfNA92aXEC7oP8DbfloQj8Cq4ce/rQHq28fRoWrTJDLtl7RKtnrYG64WvAE6iYEgwXxlKCOdNYj/J9/HJF8zF2WKINLw/yCpXVDDSyEA+z+Gf6Y0mB3cXzW3IWg0XSwVN6s=
